### ISSUE TITLE
[bug]Vim(buffer):E86 buffer not exists

### ISSUE THREAD

**Issue by yuchanns** [s1n7ax/nvim-terminal#1]
https://user-images.githubusercontent.com/25029451/128049573-16e0f8b7-79c0-4686-af82-5e4334435ef9.mov

As shown upon the movie

**Comment by s1n7ax** [comment]
Could you please update the steps to recreate this issue? Make sure to update the plugin as well. I remember similar issue which I fixed long time ago and I haven't seen this ever since.

**Comment by s1n7ax** [comment]
@yuchanns  Found the issue. When the `vim.o.hidden` is `false` this issue occurs. I recommend setting it to `true` so when you quite the buffer will stay hidden without deleting the buffer. However, this should be fixed. I will look in to it.

**Comment by yuchanns** [comment]
Thanks
