### ISSUE TITLE
Cannont exit terminal

### ISSUE THREAD

**Issue by muhammadfhadli1453** [s1n7ax/nvim-terminal#11]
I am using Neovim 0.7.2 and have installed Neovim-Terminal using Packer. I can open the terminal using <leader> + 1 or any other method. I can also toggle it. However, when I move to insert mode, I cannot switch between panes or even press [ESC]. I have to execute `exit` to close the terminal. I use Bash for my terminal. Please help me.

**Comment by s1n7ax** [comment]
https://vi.stackexchange.com/a/4922
