### ISSUE TITLE
executing the exit command keeps the terminal split. add an way to close it with the terminal

### ISSUE THREAD

**Issue by sajjathossain** [s1n7ax/nvim-terminal#12]
**When the terminal is open:**

![SCR-20231107-jrlh](https://github.com/s1n7ax/nvim-terminal/assets/59532941/57d844d7-b99f-4045-bc77-19b6bfce2567)

**After closing the terminal:**

![SCR-20231107-jrvr](https://github.com/s1n7ax/nvim-terminal/assets/59532941/5502bebc-de03-4373-8ee8-dee9de99c1b2)

**Comment by s1n7ax** [comment]
It's probably a plugin you are using. If you close the window manually or using api, this shouldn't happen
