### ISSUE TITLE
please, disable strings numeration inside terminal

### ISSUE THREAD

**Issue by palandovalex** [s1n7ax/nvim-terminal#7]
I my vim config - there active - string numeration. When i use this plugin (https://github.com/tc50cal/vim-terminal ) - theare no numeration inside this window. This is correct behaviour. In your plugin - numeration is active. It should be fixed.

**Comment by palandovalex** [comment]
In vim-terminal 
`    setlocal nonumber`

**Comment by s1n7ax** [comment]
You can use following autocmd to remove numbers.
```autocmd TermOpen * setlocal nonumber norelativenumber```
