### ISSUE TITLE
I don't know how to switch from insert mode back to normal mode.

### ISSUE THREAD

**Issue by whxcode** [s1n7ax/nvim-terminal#8]
I use <Leader>; after opening the terminal, I press the i key to enter the insert mode, but I want to return to the normal mode, press the ESC key, and cannot switch back, what should I do?

![image](https://user-images.githubusercontent.com/44012914/184388838-c6139a81-82b5-42ac-a26f-e29566123cca.png)

**Comment by s1n7ax** [comment]
You can use <kbd>ctrl</kbd> + <kbd>\\</kbd> <kbd>ctrl</kbd> + <kbd>n</kbd> to go to normal mode. Of course you can add a easier keymap

**Comment by whxcode** [comment]
> You can use ctrl + \ ctrl + n to go to normal mode. Of course you can add a easier keymap

Hi s1n7ax,I have tried using ctrl + \ and ctrl + n, but still cannot change the insert mode to normal mode.

**Comment by whxcode** [comment]
> You can use ctrl + \ ctrl + n to go to normal mode. Of course you can add a easier keymap
I look in the help documentation of neovim, find a statement, add it to my .vimrc file, and then I can switch between different modes normally, thank you for your help.

![image](https://user-images.githubusercontent.com/44012914/184461272-29dba33d-b8dc-4e87-84d8-f9e4541dffdd.png)
